### ISSUE TITLE
Crear Clase nodoN

### ISSUE THREAD

**Issue by nosarabs** [ucr-proyecto-integrador-redes-oper/etapa-4-redes-oper-belu-kafe#8]
Debe tener:
- [x] Buffers in / out
- [x] Socket
- [x] Puertos diferentes para cada tipo de paquete

Notas:
Token
Recibir Azules
Revisar Cola

ED:
Mapa de Pares ( key, (IP,Puerto) ) -> ( int, (string,string) )

**Comment by katherineam97** [comment]
Definir métodos de la clase:
asignarNodo() esperando solicitudes en Puerto *** para azules. 
actualizarEstructura() esperando solicitudes en Puerto *** para naranjas
comunicarAsignacion()
